### ISSUE TITLE
[Bug] Could NOT find CUnit (missing: CUNIT_LIBRARY) (found version ".-")

### ISSUE THREAD

**Issue by myfix16** [k0ekk0ek/cmake-cunit#1]
Hi, I tried the settings with VS2022, but then CMake proposed the following error:

1> [CMake] CMake Error at C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
1> [CMake]   Could NOT find CUnit (missing: CUNIT_LIBRARY) (found version ".-")
1> [CMake] Call Stack (most recent call first):
1> [CMake]   C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
1> [CMake]   cmake/Modules/FindCUnit.cmake:31 (find_package_handle_standard_args)
1> [CMake]   C:/Users/home/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:816 (_find_package)
1> [CMake]   cmake/Modules/CUnit.cmake:12 (find_package)
1> [CMake]   CMakeLists.txt:36 (include)
1> [CMake] -- Configuring incomplete, errors occurred!

**Comment by k0ekk0ek** [comment]
Hi @myfix16. I haven't used this myself in quite a while. Seems like a bug with version parsing. You may want to extract the version used here: https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/cmake/Modules/FindCUnit.cmake. That version is seeing active use.

**Comment by myfix16** [comment]
Thanks. Solved using a fork of CUnit with CMake refinement.
